In [1]:
import pandas as pd
import numpy as np
import os

In [17]:
#navigate to parent directory
parent_dir = os.path.dirname(os.getcwd())

#setting the filenames
training_file = os.path.join(parent_dir, '00_Dataset_Preparation/outputs/training_dataset.csv')
testing_file  = os.path.join(parent_dir, '00_Dataset_Preparation/outputs/testing_dataset.csv')

#opening the files
training_df = pd.read_csv(training_file)
testing_df  = pd.read_csv(testing_file)

In [18]:
training_df.head()

,utterance,intent,entity_type,entity_value,start_offset,end_offset,category,tags
0,how can I cancel purchase 113542617735902?,cancel_order,order_id,113542617735902,26.0,41.0,ORDER,BIL
1,can you help me canceling purchase 00004587345?,cancel_order,order_id,00004587345,35.0,46.0,ORDER,BIL
2,i want assistance to cancel purchase 732201349959,cancel_order,order_id,732201349959,37.0,49.0,ORDER,BLQ
3,i want assistance to cancel order 732201349959,cancel_order,order_id,732201349959,34.0,46.0,ORDER,BQ
4,"I don't want my last item, help me cancel orde...",cancel_order,order_id,370795561790,48.0,60.0,ORDER,BCLN

In [19]:
testing_df.head()

,utterance,intent,entity_type,entity_value,start_offset,end_offset,category,tags
0,I do not know how I can cancel purchase 00123842,cancel_order,order_id,00123842,40.0,48.0,ORDER,BEL
1,help to cancel purchase 00004587345,cancel_order,order_id,00004587345,24.0,35.0,ORDER,BL
2,cancelling purchase 00123842,cancel_order,order_id,00123842,20.0,28.0,ORDER,BKL
3,cancel purchase 00004587345,cancel_order,order_id,00004587345,16.0,27.0,ORDER,BKL
4,I don't know how to cancel order 732201349959,cancel_order,order_id,732201349959,34.0,46.0,ORDER,BZ

In [21]:
def dataset_preprocess(input_df):
    # drop other columns
    # keep only utterance, intent and tags
    df = input_df[['utterance','intent', 'tags']]

    df['encoded_intent'] = df['intent'].astype('category').cat.codes
    df['labels'] = df['tags'].apply(lambda x: [1 if letter in x else 0 for letter in 'QPWKBCIMLEZ'])

    columns_to_drop = ['intent', 'tags']
    new_df = df.drop(columns_to_drop, axis=1)
    # new_df.head()

    return new_df

In [28]:
preprocessed_train_df = dataset_preprocess(training_df)
preprocessed_test_df = dataset_preprocess(testing_df)

/tmp/ipykernel_137064/3365168205.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['encoded_intent'] = df['intent'].astype('category').cat.codes
/tmp/ipykernel_137064/3365168205.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['labels'] = df['tags'].apply(lambda x: [1 if letter in x else 0 for letter in 'QPWKBCIMLEZ'])
/tmp/ipykernel_137064/3365168205.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['encoded_intent'] = df['intent'].astype('category').cat.codes
/tmp/ipykernel_137064/3365168205.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['labels'] = df['tags'].apply(lambda x: [1 if letter in x else 0 for letter in 'QPWKBCIMLEZ'])

In [29]:
preprocessed_train_df

,utterance,encoded_intent,labels
0,how can I cancel purchase 113542617735902?,0,"[0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0]"
1,can you help me canceling purchase 00004587345?,0,"[0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0]"
2,i want assistance to cancel purchase 732201349959,0,"[1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0]"
3,i want assistance to cancel order 732201349959,0,"[1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]"
4,"I don't want my last item, help me cancel orde...",0,"[0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0]"
...,...,...,...
4575,I am waiting for a rebate of 299 dollars,18,"[0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0]"
4576,I am waiting for a compensation of 1200 dollars,18,"[0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0]"
4577,I expect a compensation of 160 dollars,18,"[0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0]"
4578,I am wating for a reimbursement of $350,18,"[0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1]"
4579,help seeing if there is anything new on my rebate,18,"[0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0]"

In [30]:
preprocessed_test_df

,utterance,encoded_intent,labels
0,I do not know how I can cancel purchase 00123842,0,"[0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0]"
1,help to cancel purchase 00004587345,0,"[0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0]"
2,cancelling purchase 00123842,0,"[0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0]"
3,cancel purchase 00004587345,0,"[0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0]"
4,I don't know how to cancel order 732201349959,0,"[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1]"
...,...,...,...
560,I'm waiting for a compensation of $1200,18,"[1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0]"
561,i expect a refund of 350 dollars,18,"[1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]"
562,I am waiting for a restitution of 299 dollars,18,"[0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0]"
563,I am waiting for a bloody compensation of 160 ...,18,"[0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0]"
564,I don't know how I can check the status of the...,18,"[0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0]"

In [32]:
# Export the DataFrame to a CSV file
preprocessed_train_df.to_csv('./outputs/training_dataset.csv', index=False)
preprocessed_test_df.to_csv('./outputs/testing_dataset.csv', index=False)